FROM node:latest

WORKDIR /usr/src/app/

COPY package.json ./
RUN npm install --silent --no-cache

COPY ./ ./

RUN apt-get update && apt-get install -y xsel

ENV VUE_APP_NO_MOCK true

CMD ["npm", "run", "start"]
