const api = {
  Login: '/login',
  Logout: '/logout',
  // 全部病人
  patientAll: '/patient/all',
  patientQueryById: '/patient/queryById',
  patientQuery: '/patient/query',
  patientAdd: '/patient/add',
  patientGetPatientReport: '/patient/getPatientReport',
  // 统计报表
  statsAll: '/stats/all',
  statsPatients: '/stats/patients',
  statsPlans: '/stats/plans',
  // 健康档案
  recordLatest: '/record/latest',
  recordAll: '/record/all',
  recordDetail: '/record/detail',
  recordAdd: '/record/add',
  // 评估筛选
  assessmentLatest: '/assessment/latest',
  assessmentAll: '/assessment/all',
  assessmentAssess: '/assessment/assess',
  // 健康管理方案
  planAll: '/plan/all',
  planDetail: '/plan/detail',
  planAdd: '/plan/add',
  // 其他
  ForgePassword: '/auth/forge-password',
  Register: '/register',
  twoStepCode: '/auth/2step-code',
  SendSms: '/account/sms',
  SendSmsErr: '/account/sms_err',
  UserInfo: '/user/info',
  User: '/user',
  Role: '/role',
  Service: '/service',
  Permission: '/permission',
  PermissionNoPager: '/permission/no-pager',
  OrgTree: '/org/tree',
}
export default api
